### ISSUE TITLE
Move user to another loop

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#352]
A host can move a user to another loop.

The host must be an admin on both loops.

Create a new page to select the loop the user will move to.

**Comment by lil5** [comment]
@paloeka If this will only be used to move all users in a loop to another (a merge of 2 loops) Then it will be better to allow a host to do that

**Comment by paloeka** [comment]
No, in the end a host will need to move individual users between loops. In case a loop splits for example. I think the best way to approach this issue is that a participant will be copied to the other chain.
Example: Participant (User_Id 10) is linked to Loop Chain_Id 20. Loop host (User_Id 11) of  Chain_Id 20 hosts besides that loop also  Chain_Id 21 and  Chain_Id 22. User_Id 10 is to be moved to  Chain_Id 21. User_Id 11 gets a pop-up message if they want to 
move User_Id 10 or copy.

The merge of a loop is probably not happening not too often, and is mostly a result of the Big Migration. If Loops will merge in the future, than individually hosts could be able to do this manually, by the description above. And if they then, with the fuction above they can delete the loop/chain.

**Comment by paloeka** [comment]
Text for infobutton: 

As a host of multiple loops, you can move participants between Loops. Select a participant and the Loop you want them to transfer to.

**Comment by lil5** [comment]
@paloeka This is now available on acceptance!
