### ISSUE TITLE
Kimberley UX suggestions

### ISSUE THREAD

**Issue by paloeka** [the-clothing-loop/website#478]
- [x] Topheader navigation changes between different pages, Kimberley suggested to have ‘Find a Loop’ everywhere (not only when you are logged out on the home page)
- [x] #488
- [x] ~~Click on circle on map should get different colour. To see which circles are looked at/activated.~~ #486 
- [x] ~~Move over list should also correspond on map. Could be a bit similar to the point before~~ #486
- [x] #489
- [x] Sign up confirmation page: [about] should be [FAQ]
- [x] #520
- [x] Check traffic for [FAQ] and [about] in Goatcounter,
- [ ] and possibly swap it
- [x] [Donate] and [Events] switch places in the top bar
- [x] Button to [About] on FAQ page

**Comment by lil5** [comment]
> Button to [About] on FAQ page

New viewers of the website should first go to the **about** page and then the FAQ, I've added a link to the FAQ in the About page instead:
https://github.com/the-clothing-loop/website/commit/1d7ac04f2e62701d56324dcfe0fca9f4084b9890

I can understand if hosts what to see the FAQ first, @paloeka should I change the nav bar _only_ for logged in users that they see the FAQ instead of the About page?

**Comment by paloeka** [comment]
I think it is good for hosts to see the FAQ button instead of the About page. They can see the about page also in the Footer of the website.

The place of the FAQ in the about page should be on top of the page (above the video/under the title). This makes it a prominent position. The FAQ button should also stand out a bit more, as it is not related to the About per se.
