### ISSUE TITLE
Fixes for app

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#529]
### Addresses

Translations:

- [x] Addresses = Adres
- [x] Phone Number = Telefoonnummer
- [x] Show at the  names where the bags, the text “Tas *number*” (e.g. Tas 1)

### Addresses sub

- [x] Emailadresses also do not need to be shown
- [x] Interested size does not necessary
- [x] G-icon is not clear it redirect to Google maps/map app maybe use  for icon (https://icons8.com/icon/set/map/ios-filled)

Add Question mark button: 
Text: 
De volgorde is door de host gemaakt op de website. Pas jij beter op een andere plek? Stuur dan een berichtje naar jouw host.

### Bags

- [x] Bag (as Title on top) = Waar is de tas?
- [ ] Bag (as icon bottom) = Tas
- [ ] Change Bag Holder = Wie heeft de tas?
- [ ] Select the new bag holder = (may be deleted)

- [ ] Be able to click on the bag-with-number icon to open page. User should be able to click on the bagicon in the tab of bags. This action should open the page of the user who is having the bag, with their information.
- [ ] People looking for the right name: it would be nice if there is a search button where people could type in the name and order number was also shown. (possible if easy the list of names shown is not from top to bottom, but around participants name)
- [x] The white space between the names could also be less. (so more compact)
- [x] How can a bag be deleted? / the Create button preferable only available for hosts
- [x] How is the order of bags decided?
- [x] Date of when the bag is received should be in the place of address

### Bulky items

- [x] It is unclear how to “reserve” an item or show interest. Maybe adding the option that somebody can click “interested”, get a pop-up message: “If you are interested please send *name* a message” and others can see how is interested. 
- [ ] In this showing the name is good, showing address unnecessary. The link to the profile is really good. 
- [x] Time is also unnecessary (date is)

**Comment by lil5** [comment]
> Emailadresses also do not need to be shown

@paloeka should the host be able to see email addresses?

**Comment by lil5** [comment]
> Be able to click on the bag-with-number icon to open page
@paloeka I don't know what you mean here

**Comment by lil5** [comment]
> How can a bag be deleted?

Click the edit button, or long press on the bag to show the **edit** and **delete** buttons

**Comment by lil5** [comment]
@paloeka I'm considering using this as a replacement with a search input:

https://ionicframework.com/docs/api/modal#sheet-modal

**Comment by paloeka** [comment]
@lil5 Host do not have to see interested sizes or emailaddresses in the app. If they want to see them, they can go onto the website

**Comment by lil5** [comment]
> How is the order of bags decided?

By which bag is created first: First created is on top, last created is on the bottom

**Comment by paloeka** [comment]
I think the first design of the bags as tiles in the screen works best.

You want to do two things here:
1. You want to see who has a bag and since when (this is not always the same date as you put it to somebodies name). A participant or host should be able to edit the date. This is best to just see on the page of Where is the Bag?
2. It would be nice if you could click on the tile and have a pop-up screen with the information of point 1 + a button with the name of the bagholder, somebody could click on to see the information of that person who holds the bag. 


PS: there is also maybe a point 3, we could discuss in the weekly meeting that came up with the interviews. And that is that host  are able to see who was the bagholder before the current bagholder, up to 2 or three previous bagholders. This is also more for a future update if we are going to do anything about it. We can discuss it in detail in the weekly meeting or the (beta testing) rapport meeting.

**Comment by paloeka** [comment]
> > Emailadresses also do not need to be shown
> > Interested size does not necessary
> 
> @paloeka should the host be able to see email addresses or Interested sizes?

They can see this on the website. I am thinking that we maybe should give hosts the option in their settings a box that they can click of the information participants are able to see. We can discuss it more in the betatesting rapport meeting

**Comment by paloeka** [comment]
> @paloeka I'm considering using this as a replacement with a search input:
> 
> https://ionicframework.com/docs/api/modal#sheet-modal

Looks good!

**Comment by lil5** [comment]
> The white space between the names could also be less. (so more compact)

This won't be a good experience for mobile users a fear, It still needs to be possible to be used with fingers, we can discuss this more next meeting.

**Comment by paloeka** [comment]
> Instead of adding new pages for everything I'm add the your requested functionality in the pages and dialogs we already have. Too many pages can be unhandy for mobile users.
> 
> Below you see;
> 
> 1. Date of delivery being editable
> 2. A search bar that is only shown on loops larger than 15 (can be changed)
> 3. The selected participant has their address color changed and their name set to semi bold
> 
> ![Image](https://user-images.githubusercontent.com/17646836/253966852-11c1bf73-fce3-4173-b6f3-eeef7e947e4a.png)

1. Good that the date is editable
2. The search bar looks good. I think it can already be there, always, or if the Loop has more than 5 participants. 
3. This looks good. It is nice that you can find yourselve a bit more quickly in the list. About the address, this was also something I wanted to discuss in that meeting. I think it is unnecessary to show the addres. What is maybe more important to show here is "where is the bag" so that you could see in this list who has a bag and which bag

**Comment by lil5** [comment]
This issue is followed up by Report Beta Testing v1
